user root;
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    #access_log    /dev/stdout;
    error_log    /dev/stdout;
    include       mime.types;
    default_type  application/octet-stream;

    fastcgi_buffers 8 16k;
    fastcgi_buffer_size 32k;
    fastcgi_connect_timeout 90s;
    fastcgi_send_timeout 90s;
    fastcgi_read_timeout 90s;
    proxy_read_timeout 90s;
    client_max_body_size 100M;

    map $remote_addr $log_ip {
        "127.0.0.1" 0;
        default 1;
    }

    log_format main '$http_x_forwarded_for [$time_local] "$request" $status $body_bytes_sent "$http_referer"  "$http_user_agent"';

    server {
        # we use port 80 here to work with our docker config but you can configure it to any port you want, just remember to update the dockerfile accordingly
		listen 80;

    	index index.php index.html;

        # your application here
    	server_name app;

    	error_log  /var/log/nginx/error.log;

    	access_log /var/log/nginx/access.log main if=$log_ip;

        # this should be the path of your public folder in laravel which from our dockerfile it would be /var/www/public
    	root /var/www/public;

        location = /favicon.ico {
            log_not_found off;
            access_log off;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
            expires max;
            log_not_found off;
            try_files $uri /index.php?$query_string;
        }

        location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
        }

		location ~ \.php$ {
			try_files $uri =404;
			fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php/php-fpm.sock;
        	fastcgi_index index.php;
        	include fastcgi_params;
        	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        	fastcgi_param PATH_INFO $fastcgi_path_info;
		    fastcgi_buffering on;

            fastcgi_buffers 8 16k;
            fastcgi_buffer_size 32k;
            fastcgi_connect_timeout 90s;
            fastcgi_send_timeout 90s;
            fastcgi_read_timeout 90s;
            proxy_read_timeout 90s;
		}

		location / {
			try_files $uri $uri/ /index.php?$query_string;
        	gzip_static on;
		}
    }
}
